### PR TITLE
Personal Access Token can be provide using secret text Credential

### LINKED ISSUE #216: How to use a Personal Access Token?
See also: https://github.com/jenkinsci/stashnotifier-plugin/issues/24

It is now possible to authenticate against the [Bitbucket API with a Personal Access Token](https://confluence.atlassian.com/bitbucketserver059/personal-access-tokens-949254787.html?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash#Personalaccesstokens-usingpersonalaccesstokens).

How to do that using this plugin?

### PR DESCRIPTION
**Pull request by noxo**
Bitbucket Personal Access token can be provided using "secret text" Credential

https://github.com/jenkinsci/stashnotifier-plugin/issues/216

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by scaytrase** [comment]
No clue why javadoc fails. Looks good for me, locally everything builds OK

**Review by scaytrase — APPROVED** [review]

**Comment by scaytrase** [comment]
@noxo since I've no own Jenkins installation at the moment, I have to ask whether you tried to install this patched plugin on your jenkins installation and tested it ?

**Comment by noxo** [comment]
@scaytrase yeah, i've tried the "patched" plugin on Jenkins with plain text credentials and access token.. both works for me. I sneaked in small clean up, but everything should be there now.

**Comment by scaytrase** [comment]
Thanks @noxo

**Comment by scaytrase** [comment]
Looks like I've managed to find the problem with javadoc, fixed it in the 1.x branch

**Comment by scaytrase** [comment]
released as 1.24, please verify

**Pull request merged**
