### PR TITLE
Fix #97 - Fix credentials resolution in global configuration

### LINKED ISSUE #95: Notifications not sent when using Build Flow job
When using the Build Flow job template, pull requests do not get notified on Stash unless the 'Flow run needs a workspace' is ticked.

### LINKED ISSUE #97: Stash notifier 1.10.2 continues to not work with the credentials plugin
Getting authorization failure messages from stash and the plug-in doesn't give the option to pick any credentials that are installed on the Jenkins system to use for authorization. 
screen shot 2016-02-08 at 2 33 52 pm

Tried this in chrome and safari to rule any weird browser weirdness as well.

### PR DESCRIPTION
**Pull request by fvogler**
Fix credentials resolution in global configuration and used global credentials as fallback if not configured in project (See #97).

### CODE REVIEW

**Comment by scaytrase** [comment]
@fvogler I'm not sure you mentioned correct issue within commit message. Please re-check it and reword if needed.

Here is the *hpi* built with your fork. You can use it for test and until bugfix version is released if needed.

[stashNotifier-1.10.2.hpi.zip](https://github.com/jenkinsci/stashnotifier-plugin/files/122634/stashNotifier-1.10.2.hpi.zip)

Also I'm calling @stevengssns and @ma77h1a5 to test this patched hpi to check this not break your changes.

**Comment by fvogler** [comment]
Hi,
in my opinion the issue reference is right. The screen shot looks like the same as in my installation and the described behaviour is similar.
After a deeper look at the issue tracker, I found some related closed issues #86, #78.

After all I think there aren't any additional changes necessary.

Regards
Florian

By the way: Can you check your code formatting. The indentions of the StashNotifier.java file are messy. Maybe a problem with tabs and spaces? (It was hard to resist to reformat the file ;-) )

**Comment by scaytrase** [comment]
The problem is that #95 you mention in the commit message does not match the #97 that mentioned in PR. Also #95 does not belongs to credentials currently - to Build Flow plugin only.

Closed issues #86 and #78 were tested to be fixed, so I've called their participants to check your patch does not brake their setup.

Yes, formatting is weird, but I'm not initial developer, but maintainer for now. I think reformatting is wasting time, since I'm intended to writer 2.0 from scratch

**Comment by DemonTPx** [comment]
The hpi you provided, @scaytrase, fixes the problem for me. :+1:

**Comment by fvogler** [comment]
Yes you are right. Sorry. Will fix it today.

**Comment by stevengssns** [comment]
I'll try to test for regressions during the weekend (no promises though).

At first sight the code simply seems to add an extra default, so it should probably be fine.

**Comment by fvogler** [comment]
Changed the message of my commit. Had to make a forced push.
Due to the test failures:
I'm not an expert in jenkins testing and not aware of your compatibility strategy for hudson, but for me it looks like a problem with the test setup (mocking). By the way there is newer version (2.3) of org.jenkins-ci.plugins:plugin available.
Sorry have no time for further investigation.

**Comment by ckulla** [comment]
Experience this issue as well

**Comment by scaytrase** [comment]
[stashNotifier-1.10.2.hpi.zip](https://github.com/jenkinsci/stashnotifier-plugin/files/142271/stashNotifier-1.10.2.hpi.zip)

Here is the updated patched HPI which I'm going to merge and release if some of you check it one more time.

There is a small fix which I hope does influence nothing as configuration currently prohibits selecting non-plaintext credentials

https://github.com/jenkinsci/stashnotifier-plugin/commit/220d3f8857a8e996d0f21c142c7f0a0e88ad9c26

If all OK I'll spend a bit more time to merge and put this to plugins repo

**Comment by rajeshgupthar** [comment]
@scaytrase the provided hpi file, works for me too. Thanks :)

**Comment by nicoddemus** [comment]
Worked for us too, thanks! :smile:

**Comment by almalki** [comment]
@scaytrase we used the provided build and it still does not list the credentials (password creds)

image

image

image

**Comment by scaytrase** [comment]
@almalki  could you please copy the plugin version from plugin list page?

**Comment by almalki** [comment]
@scaytrase 
	
Stash Notifier
This plugin notifies a Stash server of build results.
	1.10.2	


image

**Comment by scaytrase** [comment]
this does not looks like snapshot build. grap the HPI from the thread and install it manually please. Fixed version will be relised later soon to stable repo.

**Comment by almalki** [comment]
I placed this file: https://github.com/jenkinsci/stashnotifier-plugin/files/142271/stashNotifier-1.10.2.hpi.zip
inside the plugins directory after uninstalling the previous version (which I actually uploaded using the upload form) and restarted the server.

The exploded dir show that the installed version was built on 
```
#Generated by Maven
#Tue Feb 23 13:17:11 MSK 2016
version=1.10.2
groupId=org.jenkins-ci.plugins
artifactId=stashNotifier
```

is'nt it the same version? It still does not work.

Thanks for the support.

**Comment by scaytrase** [comment]
extract the zip, github does not allow me to uplpoad hpi directly. the most right way is to install the plugin via jenkins web plugin manager interface

**Comment by almalki** [comment]
@scaytrase 
I did some troubleshooting and found out that it works with freestyle projects. But the project I have is "Freestyle multi-branch project" using "Multi-Branch Project Plugin". The plugin actually works fine inside specific branch configuration, but not the parent.

**Comment by scaytrase** [comment]
@almalki I can't tell you anything until I'm sure you have the fixed version installed

**Comment by scaytrase** [comment]
Relased as 1.10.4 

http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/stashNotifier/1.10.4/

**Pull request closed without merging**
