### PR TITLE
Job specific ignore unverified ssl

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by scaytrase** [comment]
to fix findbug error you should replace on line 425 (https://github.com/jenkinsci/stashnotifier-plugin/pull/185/files#diff-9905a5d95ec4490fc08dccacee897bc2R425)

```java
ignoreUnverifiedSSL ? SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER : null
```
with
```java
SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER
```

since it's known that `ignoreUnverifiedSSL` is true inside this condition

**Comment by johnjohndoe** [comment]
Now, I understand. Thank you. Pushed.

**Comment by scaytrase** [comment]
Looks green. Does it still have a bug?

**Comment by johnjohndoe** [comment]
Not sure. The error message differs:

> [Pipeline] notifyBitbucket
> 
> Notifying Stash at "https://stash.example.com"
> Failed to notify Stash for commit fb25ccf2f328fb7a2c082770671e61ac70b9c94f ({"errors":[{"context":null,"message":"Authentifizierung fehlgeschlagen. Bitte überprüfen Sie Ihre Anmeldedaten und versuchen Sie es erneut.","exceptionName":null}]})

This is when `Ignore unverified SSL certificates` in the global settings is checked.
If the option is unchecked the `SSLHandshakeException` is thrown.

**Comment by scaytrase** [comment]
Looks like jenkins reached your bitbucket server, but fails to authenticate

**Comment by johnjohndoe** [comment]
Yes, it looks like. - When I install v.1.13 the `SSLHandshakeException` is thrown regardless of the option checked or unchecked. - I will try the patched version on a Jenkins 1.6 instance I have available.

**Comment by johnjohndoe** [comment]
The patched version works on Jenkins 1.6 (global setting checked, job specific setting unchecked):

> Notifying Stash at "https://stash.example.com"
> Notified Stash for commit with id fb25ccf2f328fb7a2c082770671e61ac70b9c94f

**Review by scaytrase — APPROVED** [review]

**Comment by johnjohndoe** [comment]
Side note for other people trying this: Since I executed the same job over and over at some point I hit a limit on the Stash instance. Than the error message changed somewhat:

> Notifying Stash at "https://stash.example.com"
> 
> Failed to notify Stash for commit fb25ccf2f328fb7a2c082770671e61ac70b9c94f ({"errors":[{"context":null,"message":"CAPTCHA erforderlich. Für Ihr Stash Konto ist eine CAPTCHA-Eingabe erforderlich, bevor Sie sich wieder anmelden können. Grund hierfür sind normalerweise zu viele Anmeldeversuche mit einem falschen Passwort.\nWenn Sie aktuell über einen Browser bei Stash angemeldet sind, müssen Sie sich abmelden und erneut anmelden, um die CAPTCHA-Eingabe zu deaktivieren.\n\nWeitere Informationen finden Sie hier: Stash unter https://stash.example.com.","exceptionName":null}]})

To resolve this you need to visit the actual Stash website and login with the server user once. The login page will prompt you to enter a CAPTCHA for security reasons.

---

Still my Stash instance does **not** accept the credentials from Jenkins 2.97. The same credentials are used to checkout the commit - which succeeds. 😕

**Comment by johnjohndoe** [comment]
# Solution

I found out that this plugin refers to the **Username with password** credentials (shown in the screenshot) whereas the **Git checkout** refers to the **SSH** credentials.

Jenkins 2 credentials


It appears that the password of the **Username** credentials was **wrong**. Once I **updated** the password the Jenkins -> Stash communication worked.

**Pull request merged**
