### PR TITLE
Use singleton of JenkinsLocationConfiguration

### LINKED ISSUE #210: JENKINS-54881  Stash Notifier Plugin doesn't set the Jenkins Root URL in stash though Jenkins URL is set in Jenkins Location in Global System Configuration
Repost from https://issues.jenkins-ci.org/browse/JENKINS-54881

Sorry for spamming, but there has been no activity on the JIRA for this component for almost a year now/

### PR DESCRIPTION
**Pull request by jakub-bochenski**
fixes #210, JENKINS-54881 
c.f. https://issues.jenkins-ci.org/browse/JENKINS-52983?focusedCommentId=347707&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-347707

### CODE REVIEW

**Comment by scaytrase** [comment]
It looks like this change breaks some tests because of impossibility to instantiate class via `.get()`

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fstashnotifier-plugin/detail/PR-211/1/tests

```
Stacktrace
java.lang.NullPointerException
at jenkins.model.JenkinsLocationConfiguration.get(JenkinsLocationConfiguration.java:46)
at org.jenkinsci.plugins.stashNotifier.StashNotifier.<init>(StashNotifier.java:154)
at org.jenkinsci.plugins.stashNotifier.StashNotifierTest.buildStashNotifier(StashNotifierTest.java:79)
at org.jenkinsci.plugins.stashNotifier.StashNotifierTest.buildStashNotifier(StashNotifierTest.java:73)
at org.jenkinsci.plugins.stashNotifier.StashNotifierTest.setUp(StashNotifierTest.java:164)
```

**Comment by scaytrase** [comment]
I think some mocks should be set up like was done before for `Jenkins` static calls

https://github.com/jenkinsci/stashnotifier-plugin/blob/release/1.x/src/test/java/org/jenkinsci/plugins/stashNotifier/StashNotifierTest.java#L100

**Comment by jakub-bochenski** [comment]
OK, will try to take care of tests

**Comment by jakub-bochenski** [comment]
> I think some mocks should be set up like was done before for Jenkins static calls

I don't really like to use mock to implement mere stubs. What I did was add a  new package-private constructor that lets you override the value in tests

**Comment by jakub-bochenski** [comment]
Wanted to try out this PR, but unfortunately this plugin doesn't publish incremental builds :( https://jenkins.io/blog/2018/05/15/incremental-deployment/

**Comment by scaytrase** [comment]
You can try HPI built here 

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fstashnotifier-plugin/detail/PR-211/3/artifacts

**Comment by jakub-bochenski** [comment]
I know, but installing things manually is so 90's. 
I'd rather send you a PR to enable incrementals, unless you can merge this before that :)

**Comment by scaytrase** [comment]
I've read the links you gave carefully and I see the PR to enable incrementals as a proper variant. I will be glad to review and accept it. Thank you in advance

**Comment by jakub-bochenski** [comment]
> I've read the links you gave carefully and I see the PR to enable incrementals as a proper variant. I will be glad to review and accept it. Thank you in advance

There it is: #213

**Comment by jakub-bochenski** [comment]
Rebased over #213 to make build results of this PR available

**Comment by scaytrase** [comment]
Great job, @jakub-bochenski Thank you!

**Comment by scaytrase** [comment]
I'm on vacation right not, so I can release this only at the end of next week. Can you be happy with incrementals until then?

**Comment by jakub-bochenski** [comment]
Sure, thanks for the fast turnover, and sorry for bugging you while on vacation

**Comment by scaytrase** [comment]
Not a real problem. I would release it now if i can, but I've just left all releasing stuff at home. Thank you again for improvements

**Comment by scaytrase** [comment]
@jakub-bochenski I've released 1.15. Sorry for long delay.

Great idea of `${revision}${changelist}` in `pom.xml` was overriden by maven deploy plugin :(

**Comment by jakub-bochenski** [comment]
> @jakub-bochenski I've released 1.15. Sorry for long delay.

no problem

> Great idea of ${revision}${changelist} in pom.xml was overriden by maven deploy plugin :(

That wasn't my idea :) I would expect this is either a misconfiguration of deploy plugin in this project, or a bug in the incremental feature of the jenkins super pom

**Comment by scaytrase** [comment]
Hm, I'll try to figure out. It worked the same way several years I maintain this plugin

**Comment by jakub-bochenski** [comment]
> Hm, I'll try to figure out. It worked the same way several years I maintain this plugin

That's how release plugin works by default, yes. Yet I would expect the people programming the incrementals feature to handle it so that you don't have to correct it after each release.
C.f. https://github.com/jenkinsci/incrementals-tools#running-maven-releases I'm not sure ATM if `incrementals:reincrementalify `  should happen automatically or is another goal to run explicitly.

EDIT: I guess you need to run it manually, since the parent pom is 3.10 and this should happen automatically for 3.18+

**Comment by scaytrase** [comment]
Actually deploy plugin updates versions for me automatically too (all these commits like `prepare next development iteration` are automagic). But I think this is somehow needed for incrementals CI server in order to produces incremental HPI builds with correct versioning

**Comment by scaytrase** [comment]
I think I need just review my release process. I've set it up years ago, things may change since then )

**Comment by jakub-bochenski** [comment]
> Actually deploy plugin updates versions for me automatically too (all these commits like prepare next development iteration are automagic). 

That's what I mean: release plugin will overwrite the version, so you need to run (manually pre 3.18) the `incrementals:reincrementalify` to put the variable expression into the version tag again.

> I think I need just review my release process. I've set it up years ago, things may change since then )

There is no need for a major change I think. Just need to remember to run that extra goal after release and/or upgrade to 3.18 parent.

**Comment by jfindlay** [comment]
@scaytrase, any updates on this?  Anything I can do to help?  I am still getting #210 on version 1.15.

**Pull request merged**
