### PR TITLE
Specify available TLS versions

### LINKED ISSUE #162: Unable to use plugin with Stash-Server demaning > TLSv1
Trying to use the plugin with a server that demands TLSv1.1 or higher resuts in the following exception:

````
Caught exception while notifying Stash with id eca1fc09cbbbb0a50c337f043f4b8215a63d8b01
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:694)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:288)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:241)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:215)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:482)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
	... 30 more
````

I think that the problem is caused by the Apache HTTP-Client. More concretely, using the [`SSLContextBuilder#useTLS`](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpclient/4.3.5/org/apache/http/conn/ssl/SSLContextBuilder.java#SSLContextBuilder.useTLS%28%29) method configures the `SSLContext` with simply `TLS`, which appearantly then defaults to TLSv1.0.

[This](https://stackoverflow.com/questions/28391798/how-to-set-tls-version-on-apache-httpclient) StackOverflow questions seems to provide a solution for the problem.

### LINKED ISSUE #170: bug/fix-tls
Hello,

I could not find PR #162 in any release tag. Is there a plan to merge this branch and release the plugin? Our Bitbucket is being upgraded to TLS 1.1+ and this fix will be needed to avoid the SSL handshake error on notifying.

Thank you!
Gleb Sapozhnikov

### PR DESCRIPTION
**Pull request by thomaseizinger**
Fixes #162.
Fixes #170.

### CODE REVIEW

**Comment by scaytrase** [comment]
Sorry for missing this PR, I'll try to process this ASAP

**Review by scaytrase — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Thanks! Who is in charge for merging the PR?
I also updated the comment so the 2nd issue will be closed as well.

**Comment by scaytrase** [comment]
I'll merge it once I ensure it deploys to my instance without any issues

**Comment by scaytrase** [comment]
Thank you, @thomaseizinger

**Pull request merged**
