### PR TITLE
added customBuildState property.

### PR DESCRIPTION
**Pull request by 0xorial**
Something that makes this plugin less coupled to 'currentBuild' global variable.

### CODE REVIEW

**Comment by scaytrase** [comment]
This was suggested long ago and I disagree with this approach. 

https://github.com/jenkinsci/stashnotifier-plugin/pull/147

This way makes the constructor just a static function to run notification process as an entry point

**Comment by 0xorial** [comment]
Thanks for information! In our case we just need to send the specific notification that is based on what we do inside our Jenkinsfile, so own logic of StashNotifier was only confusing. 

What do you think about following approach?

Split the StashNotifier class in 2: one responsible for generating and sending message to bitbucket, and another one for actual build state logic. This way signature and functionality of StashNotifier stays the same, but those who do not need all of its logic can easily opt-out by using the 'lower-level' class.

**Comment by scaytrase** [comment]
This plugin lack good refactoring indeed. If you can suggest some thoughts or work on it, I think it could be discussed, I'm fully open for good improvements

One of the ways I see to achieve it is to move out general notificaton logic to simplified classes and build two separate notifiers ontop of it - one as a classic build wrapper (freeconf post-build step) and one as pipeline\build step

**Comment by scaytrase** [comment]
I think I can open `release 2.0` discussion issue improvements discussion and close this to not confuse anyone

**Comment by scaytrase** [comment]
@0xorial please see #193

**Pull request closed without merging**
