### PR TITLE
Provide fallback for getting the instance's root URL

### LINKED ISSUE #81: Try to implement fallback to JenkinsLocationConfiguration
Despite of the fact it URL was successfully configured at the global jenkins configuration `Jenkins.getInstance.getRootUrl()` returns `null`. `JenkinsLocationConfiguration` is said to return correct value at the same time

Should fix #79 

http://stackoverflow.com/questions/15949946/programatically-access-jenkins-url

### PR DESCRIPTION
**Pull request by aaronjwood**
Should fix #81 (started from #79)

### CODE REVIEW

**Comment by scaytrase** [comment]
@aaronjwood Thank you, code looks OK, have you tested that pached plugin resoves your problem? I can build *.hpi for you if you need.

**Comment by aaronjwood** [comment]
You're welcome, I haven't tested this out yet so the .hpi would be nice :)

**Comment by aaronjwood** [comment]
Actually, looks like I will have some time today at work. Don't worry about building the .hpi. I'll do it now

**Comment by aaronjwood** [comment]
Well, so far so good. At the very beginning of my build I'm now getting `Notified Stash for commit with id 64c9310d6f58ce8f7cbb46a47e61a45f3350f1f5`

Will let you know if it notifies properly at the very end.

**Comment by aaronjwood** [comment]
Worked. Got the right notifications in stash on both build time and completion time, and no more errors about the root URL being null :)

**Comment by scaytrase** [comment]
Ok, thank you for testing. I'll merge it to develop and release it later. you can use your snapshot build until then

**Pull request merged**
