### PR TITLE
Enable Dependabot

### PR DESCRIPTION
**Pull request by offa**
Enable Dependabot dependency updates.

--------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jetersen** [comment]
This together with #279 would help keep the project up-to-date.

**Review by jetersen — APPROVED** [review]

**Comment by offa** [comment]
Ping @scaytrase

**Comment by scaytrase** [comment]
Thanks @offa! Sorry for delay, was very busy last month

**Comment by offa** [comment]
No problem, thanks for merging! :+1:

**Pull request merged**
