### PR TITLE
Jenkinsfile

### PR DESCRIPTION
**Pull request by scaytrase**
Add Jenkinsfile

### CODE REVIEW

**Comment by daniel-beck** [comment]
@scaytrase Is this meant as a Jenkinsfile for ci.jenkins.io, or for another Jenkins instance?

I'm asking because there's no node with that label on that instance (https://github.com/jenkins-infra/documentation/blob/master/ci.adoc) and we recently opened up Jenkinsfile based CI for all plugins in the jenkinsci org, so now there are builds stuck in the queue.

**Comment by scaytrase** [comment]
actually for my own, but could be replaced. we have a PR for this 

https://github.com/jenkinsci/stashnotifier-plugin/pull/165

If you verify it's correct - it could be merged immediatelly

**Comment by daniel-beck** [comment]
@scaytrase Sorry, didn't see that. Behavior should be similar, so IMO that's good to go.

**Comment by scaytrase** [comment]
merged that PR, tell if something go wrong

**Comment by daniel-beck** [comment]
@scaytrase 

https://ci.jenkins.io/job/Plugins/job/stashnotifier-plugin/ looks good 👍

**Pull request merged**
