### PR TITLE
Modernize to latest versions supported by Java 8

### PR DESCRIPTION
**Pull request by sghill**
Upgrade POM parent and `jenkins.version` to last versions that support Java 8. Builds are enabled for Java 11 and 17.
Goal is to keep the build green and follow up with a subsequent PR to modernize to current recommended versions.

This has been done by the [OpenRewrite](https://docs.openrewrite.org/) recipes at [sghill/rewrite-jenkins](https://github.com/sghill/rewrite-jenkins).

### Testing done

Ran `mvn clean verify`.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira (none)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Fixes #337
Fixes #327 
Related to #326
Fixes #322

### CODE REVIEW

**Comment by sghill** [comment]
@scaytrase I think the build may only run with the Jenkinsfile on the target branch(?).

Java 11 is required and the included Jenkinsfile configuration is recommended starting with [parent version 4.52](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.52).

**Comment by offa** [comment]
> @scaytrase I think the build may only run with the Jenkinsfile on the target branch(?).

Jenkinsfile changes require write access, otherwise they wont apply.

**Review by offa — APPROVED** [review]

**Comment by sghill** [comment]
@scaytrase based on offa's comment (thanks!) I've limited the scope of this PR to the latest versions that worked on Java 8 to keep the build green.

**Comment by sghill** [comment]
@scaytrase would you be interested in adding additional maintainers for this plugin?

**Comment by scaytrase** [comment]
@sghill I'd like to, since I'm not using Jenkins for many years for now (but still like it). But I have no idea how to grand release permissions to maintainers. I can give only repo permissions here

**Comment by sghill** [comment]
@scaytrase I'm happy to help maintain. From [Managing plugin permissions](https://www.jenkins.io/doc/developer/plugin-governance/managing-permissions/) it sounds like there are two parts - 

1. Adding me to `stashNotifier Developers` team on GitHub
2. Adding release permissions through [repository-permissions-updater](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-stashNotifier.yml). I can submit a PR here adding myself if you'd like?

My goals for maintenance would be:
1. Adopting [automated plugin release](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to make maintenance easier. I've had a good CD experience on commons-text-api-plugin (enabled in [cc850d17](https://github.com/jenkinsci/commons-text-api-plugin/commit/cc850d1794c1fbc54d8054c91de279b022ec78f5)).
2. Re-baselining every quarter to the minimum recommended Jenkins version with an automated PR like this one
3. Staying current on tooling, which usually requires fixing SpotBugs issues and deprecations
4. Minor operator improvements (additional logging for example)

For anything major happy to open a PR and leave it open for review/discussion for a week or so.

**Comment by scaytrase** [comment]
> Adding me to stashNotifier Developers team on GitHub

I have no permissions even for this one.

> I can submit a PR here adding myself if you'd like?

I'd be happy if you can drive the whole process of maintenance sharing since I don't really know all the internal kitchen for Jenkisn development. Tag me wherever one need my approve for this, I'll come

**Comment by sghill** [comment]
Requested deploy permissions in https://github.com/jenkins-infra/repository-permissions-updater/pull/3481

**Comment by scaytrase** [comment]
I've given you permissions but rolled back since it says u've already given admin via team mebmership. thanks a lot!

**Comment by sghill** [comment]
Thanks @scaytrase!

**Pull request merged**
