### PR TITLE
Make build state and build name overwritable

### LINKED ISSUE #209: Add argument for buildResult
I would like to have an argument for the buildResult which is reportet to bitbucket.

My use Case:
From pipeline A I'm stating an integration pipeline B with build(... wait: false, ...). Just after that call pipeline A terminates succesfully. From this moment on, it looks like (in Bitbucket) all the pipelines have been successfully completed. The notification about Pipeline B takes several minutes, until the checkouts in Pipeline B.
My preferred solution: Before calling build() in Pipeline A,  I want to inform Bitbucket about Pipeline B, which is INPROGRESS.

### PR DESCRIPTION
**Pull request by westarne**
Fixes #209 #241

### CODE REVIEW

**Comment by scaytrase** [comment]
@westarne did you try these changes by yourself? I hope with current approach if you run notification multiple times per build than you get single build result in bitbucket, since they will override each other

**Comment by westarne** [comment]
I have not actually imported this into Jenkins to run, yet. I think what you mean is that multiple notifications like `notifyBitbucket(buildName: "Build")` and `notifyBitbucket(buildName: "Test")` will overwrite each other. As far as I know, this is in fact the case, but you could use `notifyBitbucket(buildName: "Build", projectKey: "build")` to change this key. Maybe an option like `includeBuildNameInKey` would be good to do this automatically though.

**Comment by scaytrase** [comment]
I think you can automatically append overriden build name to the project key if any.

**Comment by westarne** [comment]
Ok i will do this later today or maybe tomorrow. I think I will rename buildState to buildStatus, too.

**Comment by westarne** [comment]
Ok, so now the buildName is appended to the key whenever it is set. I could also add this to the default build key method, so it is only used, when the projectKey is not specifically set. I actually think the latter is the better option to let the user overwrite this if he wants.

**Comment by scaytrase** [comment]
Yea, good idea

**Comment by westarne** [comment]
Ok, i've changed it now to be in the default build key only.

**Comment by westarne** [comment]
I have now tested this on my Jenkins with this code snippet, to test whether the calls are working and doing what intended:

```groovy
        notifyBitbucket(buildStatus: 'INPROGRESS', buildName: 'MY NAME')
        notifyBitbucket(buildStatus: 'SUCCESSFUL', buildName: 'MY NAME')
        notifyBitbucket(buildStatus: 'FAILED', buildName: 'MY NAME')
        notifyBitbucket(buildStatus: 'INPROGRESS', buildName: 'Build')
        notifyBitbucket(buildStatus: 'SUCCESSFUL', buildName: 'Build')
        notifyBitbucket(buildStatus: 'INPROGRESS', buildName: 'Build')
        notifyBitbucket(buildStatus: 'INPROGRESS')
        notifyBitbucket(buildStatus: 'SUCCESSFUL')
```

Status in Bitbucket:
image

So this works as intended. The builds still link as before.

**Comment by scaytrase** [comment]
ok, thank you.I'll try to get into it this week

пн, 12 авг. 2019 г., 20:19 Arne Westphal <notifications@github.com>:

**Comment by yueyehm** [comment]
@westarne btw, is it convenience for you to help making the "**_description_**" as overridable too? Current logic is using the build description, but if we could override the description when we invoke notifyStash method, it would be great.

**Comment by scaytrase** [comment]
@yueyehm I think this could be done as separater PR another issue.
@westarne sorry, I've got a bit busy these days, will release it this week

**Comment by scaytrase** [comment]
thank you @westarne

**Comment by westarne** [comment]
Thank you, too.
@yueyehm if I find the time I can make another pull request for that.

**Comment by yueyehm** [comment]
@westarne thanks very much!

**Pull request merged**
