### PR TITLE
Implementation of notification override mechanism

### PR DESCRIPTION
**Pull request by kutsal**
Implementing issue/request #107:

* Added "useJobDescription" boolean field
* Added "description" TokenMacro-compatible field to override notification sent
* Added TokenMacro macro BUILD_RESULT containing Jenkins build result

### CODE REVIEW

**Comment by scaytrase** [comment]
Also I'm calling @pixman20 here to discuss compatibility with #126 and vice-versa

**Comment by kutsal** [comment]
Yep, I just saw his PR, and I think I like his approach better -- separate message templates for different states. Only difference with mine is the added BUILD_RESULT TokenMacro that gets used as default when nothing is specified anywhere.

**Comment by pixman20** [comment]
I do prefer separate message overrides myself as well, although if I had time it'd be nice to be able to select to add an override via an "Add Override" button, which would contain a Jenkins build status, the override string, and a Stash Build Status (in order to override the mapped status in cases where a state like UNSTABLE or ABORTED in Jenkins should actually be shown as a SUCCESS in Stash, etc.).  
This is more work, but I bring it up because both of our PRs would make that more functional change to be a breaking change, whereas right now it would not be if that was done instead.

All that said, I do really like the ability to use BUILD_RESULT.  After I made my PR I actually started wishing I had that as well :).
My preference would be to use the overrides, but then add in the BUILD_RESULT macro expansion capability.

Thoughts?

**Comment by kutsal** [comment]
@pixman20 I can merge my BUILD_RESULT change into your PR and close this one.

**Comment by kutsal** [comment]
Closing this PR since @pixman20 merged my TokenMacro addition into his PR #126 which is a better implementation of this.

**Pull request closed without merging**
