### PR TITLE
enable dsl support

### PR DESCRIPTION
**Pull request by bakito**
This pull request implements a pretty dsl support for the stash notifier plugin as requested in https://github.com/jenkinsci/stashnotifier-plugin/issues/136.

For the usage see readme.md

### CODE REVIEW

**Comment by scaytrase** [comment]
hi, @bakito thank you for contribution!

Not familiar with DSL. Can we use two symbols at once, i.e have two aliases - `notifyStash`, `notifyBitbucket` ? I think this will be much easier to understand for new users to use bitbucket named alias. Other names are still not changed for BC, but new things can reflect actual names

**Review by scaytrase — APPROVED** [review]

**Comment by bakito** [comment]
Hi @scaytrase
Although the @Symbol annotation allows to define String[] as value, only the first one is used as DSL identifier.

I could change it to notifyBitbucket.

**Comment by bakito** [comment]
Correction: Both aliases are interpreted, but only the fist one is considered in the Pipeline Syntax wizard.

I could use notifyBitbucket as first and notifyStash as second.

**Review by scaytrase — APPROVED** [review]

**Comment by bakito** [comment]
How do poll request work here? Do I have to do someting or are we just waiting for merge?

**Comment by scaytrase** [comment]
@bakito All fine, I'll test your PR and merge it soon. Will be available with next release

**Comment by scaytrase** [comment]
Thank you, @bakito

**Comment by bakito** [comment]
You're welcome.
I guess you can close https://github.com/jenkinsci/stashnotifier-plugin/issues/136 now

**Pull request merged**
